/* Barkeep — the recipe book and the shelf.
 *
 * Specs follow the standard published builds (the IBA list for the classics it
 * covers). Recipes as lists of ingredients and quantities are facts; every
 * method and description line here is our own wording. Nothing is copied from
 * a recipe site or a cocktail API.
 *
 * Amounts are in ml (30 ml = 1 oz, the bar convention). A string amount is a
 * non-volume measure ("2 dashes", "top", "6 leaves") and is shown as written.
 * A third element of `true` marks an ingredient as optional: it never counts
 * against "can you make it".
 *
 * Glass codes: coupe, martini, nick, rocks, highball, collins, flute, wine,
 * mug (copper), hurricane, tiki, shot, toddy, julep, margarita, pint.
 * fx: ice, crushed, bubbles, foam, float (last colour is a float on top),
 *     salt, sugar (rims), hot, layered.
 */
(function () {
  "use strict";

  /* The shelf. `s` is the shelf it lives on, `c` its liquid colour, `k` the
   * bottle silhouette it is drawn as. PANTRY items are assumed to be in every
   * kitchen and never appear on the shelf or count as missing. */
  var SHELF = [
    // spirits
    ["vodka", "Vodka", "spirits", "#e8eef2", "tall"],
    ["gin", "Gin", "spirits", "#dfeef0", "square"],
    ["white rum", "White rum", "spirits", "#eef0ea", "tall"],
    ["dark rum", "Dark / aged rum", "spirits", "#7a3a14", "squat"],
    ["overproof rum", "Overproof rum", "spirits", "#a8581c", "squat"],
    ["rhum agricole", "Rhum agricole", "spirits", "#efe9d6", "tall"],
    ["cachaca", "Cachaça", "spirits", "#eef0e0", "tall"],
    ["tequila", "Tequila", "spirits", "#f1ecd2", "square"],
    ["mezcal", "Mezcal", "spirits", "#ece6c8", "flask"],
    ["bourbon", "Bourbon", "spirits", "#b0621c", "square"],
    ["rye", "Rye whiskey", "spirits", "#a8581a", "tall"],
    ["scotch", "Scotch", "spirits", "#c07a26", "tall"],
    ["peated scotch", "Peated Scotch", "spirits", "#b8741e", "squat"],
    ["irish whiskey", "Irish whiskey", "spirits", "#c8822a", "tall"],
    ["cognac", "Cognac / brandy", "spirits", "#9c4c18", "decanter"],
    ["apple brandy", "Apple brandy", "spirits", "#c07830", "tall"],
    ["pisco", "Pisco", "spirits", "#f0ecde", "tall"],
    ["absinthe", "Absinthe", "spirits", "#a8d86a", "tall"],

    // liqueurs
    ["orange liqueur", "Orange liqueur", "liqueurs", "#f2e4b8", "square"],
    ["maraschino", "Maraschino", "liqueurs", "#f0ecdc", "flask"],
    ["green chartreuse", "Green Chartreuse", "liqueurs", "#8ec23a", "squat"],
    ["yellow chartreuse", "Yellow Chartreuse", "liqueurs", "#e8cc3a", "squat"],
    ["benedictine", "Bénédictine", "liqueurs", "#c8902a", "squat"],
    ["drambuie", "Drambuie", "liqueurs", "#d09a30", "squat"],
    ["amaretto", "Amaretto", "liqueurs", "#a8541c", "square"],
    ["coffee liqueur", "Coffee liqueur", "liqueurs", "#2a140a", "squat"],
    ["irish cream", "Irish cream", "liqueurs", "#d8b890", "squat"],
    ["creme de menthe", "Crème de menthe", "liqueurs", "#5ed06a", "tall"],
    ["creme de cacao", "Crème de cacao", "liqueurs", "#ecdcc0", "tall"],
    ["creme de cassis", "Crème de cassis", "liqueurs", "#5a0e2a", "squat"],
    ["creme de mure", "Crème de mûre", "liqueurs", "#4a0c30", "squat"],
    ["creme de violette", "Crème de violette", "liqueurs", "#7a5ac8", "tall"],
    ["cherry liqueur", "Cherry liqueur", "liqueurs", "#7a0c1c", "squat"],
    ["apricot brandy", "Apricot liqueur", "liqueurs", "#e8902a", "squat"],
    ["raspberry liqueur", "Raspberry liqueur", "liqueurs", "#8a1030", "round"],
    ["elderflower liqueur", "Elderflower liqueur", "liqueurs", "#f2ecc0", "square"],
    ["peach schnapps", "Peach schnapps", "liqueurs", "#f8d8b0", "tall"],
    ["melon liqueur", "Melon liqueur", "liqueurs", "#5ad84a", "tall"],
    ["apple liqueur", "Sour apple liqueur", "liqueurs", "#a8e04a", "tall"],
    ["blue curacao", "Blue curaçao", "liqueurs", "#2a8ae0", "tall"],
    ["galliano", "Galliano", "liqueurs", "#f2d020", "tall"],
    ["falernum", "Falernum", "liqueurs", "#efe4c0", "tall"],
    ["pimms", "Pimm's No. 1", "liqueurs", "#8a3a1a", "tall"],

    // aperitifs, wine and beer
    ["campari", "Campari", "aperitifs", "#c8141e", "tall"],
    ["aperol", "Aperol", "aperitifs", "#f2641e", "tall"],
    ["sweet vermouth", "Sweet vermouth", "aperitifs", "#6a1a12", "tall"],
    ["dry vermouth", "Dry vermouth", "aperitifs", "#eeeccc", "tall"],
    ["lillet blanc", "Lillet Blanc", "aperitifs", "#f0d890", "squat"],
    ["fernet", "Fernet", "aperitifs", "#2a1a10", "tall"],
    ["amaro nonino", "Amaro Nonino", "aperitifs", "#c06a2a", "tall"],
    ["fino sherry", "Fino sherry", "aperitifs", "#f2e2a0", "tall"],
    ["port", "Ruby port", "aperitifs", "#5a0e1a", "tall"],
    ["sparkling wine", "Sparkling wine", "aperitifs", "#f2e2a0", "wine"],
    ["white wine", "White wine", "aperitifs", "#f2e8b0", "wine"],
    ["red wine", "Red wine", "aperitifs", "#5a0a1a", "wine"],
    ["lager", "Lager", "aperitifs", "#e8b030", "can"],

    // mixers
    ["soda water", "Soda water", "mixers", "#e8f2f6", "can"],
    ["tonic", "Tonic water", "mixers", "#eef4f6", "can"],
    ["ginger beer", "Ginger beer", "mixers", "#e8d8a0", "can"],
    ["ginger ale", "Ginger ale", "mixers", "#e8c880", "can"],
    ["cola", "Cola", "mixers", "#3a1a0c", "can"],
    ["lemon-lime soda", "Lemon-lime soda", "mixers", "#eef4dc", "can"],
    ["grapefruit soda", "Grapefruit soda", "mixers", "#f6dcd0", "can"],
    ["orange juice", "Orange juice", "mixers", "#f5a020", "carton"],
    ["pineapple juice", "Pineapple juice", "mixers", "#f5dc70", "carton"],
    ["cranberry juice", "Cranberry juice", "mixers", "#b0102a", "carton"],
    ["grapefruit juice", "Grapefruit juice", "mixers", "#f6b8a0", "carton"],
    ["tomato juice", "Tomato juice", "mixers", "#b01e14", "carton"],
    ["lemonade", "Lemonade", "mixers", "#f4ecb0", "carton"],
    ["iced tea", "Iced tea", "mixers", "#9a4a14", "carton"],

    // fresh
    ["lime", "Limes", "fresh", "#8ccf3a", "fruit"],
    ["lemon", "Lemons", "fresh", "#f2d83a", "fruit"],
    ["mint", "Mint", "fresh", "#3aa84a", "herb"],
    ["basil", "Basil", "fresh", "#2a9a3a", "herb"],
    ["ginger", "Fresh ginger", "fresh", "#e0c080", "fruit"],
    ["raspberries", "Raspberries", "fresh", "#d0204a", "fruit"],
    ["peaches", "Peaches", "fresh", "#f5a870", "fruit"],
    ["egg", "Eggs", "fresh", "#f8f0dc", "egg"],
    ["cream", "Cream", "fresh", "#f6f0e0", "carton"],
    ["espresso", "Espresso", "fresh", "#2a1408", "cup"],
    ["coffee", "Hot coffee", "fresh", "#3a1c0c", "cup"],
    ["olives", "Olives & brine", "fresh", "#8a9a3a", "jar"],
    ["cucumber", "Cucumber", "fresh", "#7ac05a", "fruit"],

    // syrups and bitters
    ["angostura", "Angostura bitters", "bitters", "#6a140a", "dasher"],
    ["orange bitters", "Orange bitters", "bitters", "#d8701a", "dasher"],
    ["peychauds", "Peychaud's bitters", "bitters", "#c01a2a", "dasher"],
    ["grenadine", "Grenadine", "bitters", "#c0102a", "tall"],
    ["orgeat", "Orgeat", "bitters", "#f2ece0", "tall"],
    ["honey", "Honey", "bitters", "#e0a020", "jar"],
    ["agave", "Agave syrup", "bitters", "#e8c070", "tall"],
    ["passion fruit syrup", "Passion fruit syrup", "bitters", "#f0a820", "tall"],
    ["cream of coconut", "Cream of coconut", "bitters", "#f6f2e8", "can"],
    ["orange flower water", "Orange flower water", "bitters", "#f2f0e8", "dasher"],
    ["worcestershire", "Worcestershire", "bitters", "#3a1a0a", "dasher"],
    ["hot sauce", "Hot sauce", "bitters", "#c01a0a", "dasher"],
    ["cider vinegar", "Cider vinegar", "bitters", "#d8a040", "tall"],

    // zero-proof: generic on purpose — the category, never a brand
    ["na gin", "Zero-proof gin", "zero", "#e4f0ec", "square"],
    ["na aperitif", "Zero-proof bitter aperitif", "zero", "#d02a24", "tall"],
    ["na sparkling", "Alcohol-free sparkling", "zero", "#f0e2a0", "wine"],
    ["na beer", "Non-alcoholic beer", "zero", "#e0b040", "can"]
  ];

  /* Advice only, never counted: the non-alcoholic bottle that can stand in
   * for each of these. A recipe gets a "make it zero-proof" line only when
   * EVERY alcoholic thing in it has a stand-in here. Non-alcoholic spirits do
   * not behave like the real thing in most specs, so a swap is a suggestion,
   * not a drink Barkeep claims you can make. */
  var SWAPS = {
    "gin": "na gin", "campari": "na aperitif", "aperol": "na aperitif",
    "sparkling wine": "na sparkling", "lager": "na beer"
  };

  var PANTRY = ["simple syrup", "sugar", "water", "hot water", "salt", "pepper", "ice"];
  var PANTRY_LABEL = {
    "simple syrup": "Simple syrup", "sugar": "Sugar", "water": "Water", "hot water": "Hot water",
    "salt": "Salt", "pepper": "Black pepper", "ice": "Ice"
  };

  /* A sensible first shelf for "Stock a starter bar": what a well-kept home
   * bar has before anyone gets serious. */
  var STARTER = ["vodka", "gin", "white rum", "tequila", "bourbon", "orange liqueur", "sweet vermouth",
    "dry vermouth", "angostura", "lime", "lemon", "soda water", "tonic", "ginger beer", "cola",
    "orange juice", "cranberry juice", "mint"];

  /* name, base, style, glass, ingredients, garnish, method, colours, fx, aka */
  function D(n, b, st, g, i, gar, m, c, fx, aka) {
    return { n: n, b: b, st: st, g: g, i: i, gar: gar, m: m, c: c, fx: fx || [], aka: aka || "" };
  }

  var DRINKS = [
    // ---------------------------------------------------------------- gin
    D("Negroni", "gin", "stirred", "rocks", [[30, "gin"], [30, "campari"], [30, "sweet vermouth"]],
      "Orange peel", "Stir everything with ice until the outside of the glass is cold, then strain over a single large cube. Twist the peel over the top.",
      ["#b3261e"], ["ice"]),
    D("Dry Martini", "gin", "stirred", "martini", [[60, "gin"], [10, "dry vermouth"], ["1 dash", "orange bitters", true]],
      "Lemon twist or an olive", "Stir long and cold, strain into a chilled glass. The drier you like it, the less vermouth.",
      ["#eef2ea"]),
    D("Dirty Martini", "gin", "stirred", "martini", [[60, "gin"], [10, "dry vermouth"], [15, "olives"]],
      "Two olives on a pick", "Stir the gin, vermouth and olive brine with ice and strain into a chilled glass.",
      ["#dcdcc0"]),
    D("Gibson", "gin", "stirred", "martini", [[60, "gin"], [10, "dry vermouth"]],
      "Cocktail onion", "A dry martini, finished with a pickled onion instead of an olive. Stir cold and strain.",
      ["#eef2ea"]),
    D("Vesper", "gin", "stirred", "martini", [[45, "gin"], [15, "vodka"], [7.5, "lillet blanc"]],
      "Long lemon peel", "Stir hard with plenty of ice and strain into a deep chilled glass.",
      ["#f2e8c4"]),
    D("Martinez", "gin", "stirred", "coupe", [[45, "gin"], [45, "sweet vermouth"], [5, "maraschino"], ["2 dashes", "orange bitters"]],
      "Lemon peel", "The martini's sweeter ancestor. Stir with ice and strain into a chilled coupe.",
      ["#8a3a1e"]),
    D("Tuxedo", "gin", "stirred", "coupe", [[30, "gin"], [30, "dry vermouth"], ["½ barspoon", "maraschino"], ["¼ barspoon", "absinthe"], ["3 dashes", "orange bitters"]],
      "Cherry and a lemon twist", "Stir everything with ice and strain into a chilled coupe.",
      ["#ecead2"]),
    D("Hanky Panky", "gin", "stirred", "coupe", [[45, "gin"], [45, "sweet vermouth"], [7.5, "fernet"]],
      "Orange peel", "Stir with ice and strain. The splash of fernet is what makes it: bitter, minty, dark.",
      ["#6e2a17"]),
    D("Gin & Tonic", "gin", "highball", "highball", [[50, "gin"], [150, "tonic"]],
      "Lime wedge", "Fill the glass with ice, pour the gin, top with cold tonic and stir once, gently.",
      ["#eef4f0"], ["ice", "bubbles"], "G&T"),
    D("Tom Collins", "gin", "highball", "collins", [[45, "gin"], [30, "lemon"], [15, "simple syrup"], [60, "soda water"]],
      "Lemon wheel and a cherry", "Shake the gin, lemon and syrup, strain over ice and lengthen with soda.",
      ["#f2f0d8"], ["ice", "bubbles"]),
    D("Gin Fizz", "gin", "fizz", "highball", [[45, "gin"], [30, "lemon"], [10, "simple syrup"], [80, "soda water"]],
      "Lemon wheel", "Shake the gin, lemon and syrup hard, strain into a chilled glass with no ice and top with soda.",
      ["#f2f0dc"], ["bubbles"]),
    D("Ramos Gin Fizz", "gin", "fizz", "collins", [[45, "gin"], [15, "lemon"], [15, "lime"], [30, "simple syrup"], [60, "cream"], [30, "egg"], ["3 dashes", "orange flower water"], [40, "soda water"]],
      "None — the foam is the garnish", "Shake without ice first, then with ice for a long time. Strain into a glass and pour the soda in slowly so the foam rises above the rim.",
      ["#f8f4e6"], ["foam"]),
    D("Gimlet", "gin", "sour", "coupe", [[60, "gin"], [22.5, "lime"], [15, "simple syrup"]],
      "Lime wheel", "Shake hard with ice and strain into a chilled coupe.",
      ["#e6f0c0"]),
    D("Southside", "gin", "sour", "coupe", [[60, "gin"], [30, "lime"], [15, "simple syrup"], ["6 leaves", "mint"]],
      "Mint leaf", "Shake everything with ice so the mint bruises, then double strain into a chilled coupe.",
      ["#d4ecb4"]),
    D("Last Word", "gin", "sour", "coupe", [[22.5, "gin"], [22.5, "green chartreuse"], [22.5, "maraschino"], [22.5, "lime"]],
      "None", "Four equal parts. Shake hard with ice and strain into a chilled coupe.",
      ["#c9dc7a"]),
    D("Aviation", "gin", "sour", "coupe", [[45, "gin"], [15, "maraschino"], [5, "creme de violette"], [15, "lemon"]],
      "Cherry", "Shake with ice and strain. The violette tints it the pale lilac of an evening sky.",
      ["#cfc6e8"]),
    D("Bee's Knees", "gin", "sour", "coupe", [[60, "gin"], [22.5, "lemon"], [22.5, "honey"]],
      "Lemon twist", "Loosen the honey with a little warm water first, then shake everything with ice and strain.",
      ["#f2e0a0"]),
    D("Bramble", "gin", "sour", "rocks", [[50, "gin"], [25, "lemon"], [12.5, "simple syrup"], [15, "creme de mure"]],
      "Blackberry and a lemon slice", "Shake the gin, lemon and syrup, strain over crushed ice, then drizzle the blackberry liqueur down through it.",
      ["#ece6cc", "#6a1f4a"], ["crushed", "layered"]),
    D("Clover Club", "gin", "sour", "coupe", [[45, "gin"], [15, "lemon"], ["4 berries", "raspberries"], [15, "simple syrup"], [20, "egg"]],
      "Raspberries on a pick", "Muddle the raspberries in the syrup, add everything else and shake without ice, then again with ice. Double strain.",
      ["#e2708a"], ["foam"]),
    D("White Lady", "gin", "sour", "coupe", [[40, "gin"], [30, "orange liqueur"], [20, "lemon"], [15, "egg", true]],
      "Lemon twist", "Shake hard with ice and strain into a chilled coupe.",
      ["#f2ead0"], ["foam"]),
    D("Corpse Reviver No. 2", "gin", "sour", "coupe", [[22.5, "gin"], [22.5, "lillet blanc"], [22.5, "orange liqueur"], [22.5, "lemon"], ["1 rinse", "absinthe"]],
      "Orange peel", "Coat the inside of a chilled coupe with absinthe and tip out the rest. Shake the rest with ice and strain in.",
      ["#f0e2a8"]),
    D("Monkey Gland", "gin", "sour", "coupe", [[50, "gin"], [30, "orange juice"], ["1 barspoon", "grenadine"], ["1 rinse", "absinthe"]],
      "Orange peel", "Rinse the glass with absinthe, shake the rest with ice and strain in.",
      ["#f09a4a"]),
    D("Singapore Sling", "gin", "tiki", "hurricane", [[30, "gin"], [15, "cherry liqueur"], [7.5, "orange liqueur"], [7.5, "benedictine"], [120, "pineapple juice"], [15, "lime"], [10, "grenadine"], ["1 dash", "angostura"]],
      "Pineapple wedge and a cherry", "Shake everything hard with ice and strain over fresh ice. Pineapple gives it a pink foamy head.",
      ["#e45a6e"], ["ice", "foam"]),
    D("Paradise", "gin", "sour", "coupe", [[35, "gin"], [20, "apricot brandy"], [15, "orange juice"]],
      "Orange twist", "Shake with ice and strain into a chilled coupe.",
      ["#f2a24a"]),
    D("Casino", "gin", "sour", "coupe", [[40, "gin"], [10, "maraschino"], [10, "lemon"], ["2 dashes", "orange bitters"]],
      "Cherry and a lemon twist", "Shake with ice and strain into a chilled coupe.",
      ["#f0eccc"]),
    D("Angel Face", "gin", "stirred", "coupe", [[30, "gin"], [30, "apricot brandy"], [30, "apple brandy"]],
      "None", "Three equal parts, stirred cold and strained into a chilled coupe.",
      ["#e8a24a"]),
    D("Gin Basil Smash", "gin", "sour", "rocks", [[60, "gin"], [22.5, "lemon"], [15, "simple syrup"], ["a handful", "basil"]],
      "Basil sprig", "Muddle the basil in the lemon and syrup, add the gin and shake hard with ice. Double strain over fresh ice.",
      ["#9cd46a"], ["ice"]),
    D("French 75", "gin", "sparkling", "flute", [[30, "gin"], [15, "lemon"], [15, "simple syrup"], [60, "sparkling wine"]],
      "Lemon twist", "Shake the gin, lemon and syrup with ice, strain into a flute and top with cold sparkling wine.",
      ["#f3e5a0"], ["bubbles"]),
    D("Suffering Bastard", "gin", "highball", "highball", [[30, "gin"], [30, "cognac"], [15, "lime"], ["1 dash", "angostura"], [120, "ginger beer"]],
      "Mint sprig and an orange slice", "Shake the gin, brandy, lime and bitters with ice, strain over fresh ice and top with ginger beer.",
      ["#d8a24a"], ["ice", "bubbles"]),

    // --------------------------------------------------------------- vodka
    D("Moscow Mule", "vodka", "highball", "mug", [[45, "vodka"], [15, "lime"], [120, "ginger beer"]],
      "Lime wheel", "Build over ice in a copper mug: vodka, lime, then ginger beer. Stir once.",
      ["#ece2c0"], ["ice", "bubbles"]),
    D("Cosmopolitan", "vodka", "sour", "martini", [[40, "vodka"], [15, "orange liqueur"], [15, "lime"], [30, "cranberry juice"]],
      "Flamed orange peel", "Shake hard with ice and strain into a chilled glass.",
      ["#e2536a"], [], "Cosmo"),
    D("Espresso Martini", "vodka", "sour", "coupe", [[50, "vodka"], [20, "coffee liqueur"], [30, "espresso"], [10, "simple syrup"]],
      "Three coffee beans", "Shake very hard with ice so the fresh espresso foams, then strain into a chilled coupe.",
      ["#2a1a12", "#c8a07a"], ["foam", "float"]),
    D("White Russian", "vodka", "creamy", "rocks", [[50, "vodka"], [20, "coffee liqueur"], [30, "cream"]],
      "None", "Pour the vodka and coffee liqueur over ice, then float the cream on top and let it drift down.",
      ["#3a1c10", "#f2e8d8"], ["ice", "float"]),
    D("Black Russian", "vodka", "stirred", "rocks", [[50, "vodka"], [20, "coffee liqueur"]],
      "None", "Pour both over ice and stir.",
      ["#2a140c"], ["ice"]),
    D("Bloody Mary", "vodka", "savory", "highball", [[45, "vodka"], [90, "tomato juice"], [15, "lemon"], ["2 dashes", "worcestershire"], ["2 dashes", "hot sauce"], ["a pinch", "salt"], ["a pinch", "pepper"]],
      "Celery stalk and a lemon wedge", "Roll it gently between two tins rather than shaking, so the tomato stays thick. Pour over ice.",
      ["#b8231e"], ["ice"]),
    D("Screwdriver", "vodka", "highball", "highball", [[50, "vodka"], [100, "orange juice"]],
      "Orange slice", "Build over ice and stir.",
      ["#f5a830"], ["ice"]),
    D("Greyhound", "vodka", "highball", "highball", [[50, "vodka"], [120, "grapefruit juice"]],
      "Grapefruit wedge", "Build over ice and stir.",
      ["#f6c2a8"], ["ice"]),
    D("Salty Dog", "vodka", "highball", "highball", [[50, "vodka"], [120, "grapefruit juice"], ["rim", "salt"]],
      "Salted rim", "Salt half the rim, fill with ice, then build the vodka and grapefruit.",
      ["#f6c2a8"], ["ice", "salt"]),
    D("Sea Breeze", "vodka", "highball", "highball", [[40, "vodka"], [120, "cranberry juice"], [30, "grapefruit juice"]],
      "Lime wedge", "Build over ice and stir.",
      ["#d0405a"], ["ice"]),
    D("Cape Codder", "vodka", "highball", "highball", [[45, "vodka"], [120, "cranberry juice"]],
      "Lime wedge", "Build over ice and stir.",
      ["#b8203a"], ["ice"], "Vodka Cranberry"),
    D("Bay Breeze", "vodka", "highball", "highball", [[45, "vodka"], [90, "cranberry juice"], [30, "pineapple juice"]],
      "Lime wedge", "Build over ice and stir.",
      ["#d8506a"], ["ice"]),
    D("Madras", "vodka", "highball", "highball", [[45, "vodka"], [90, "cranberry juice"], [30, "orange juice"]],
      "Lime wedge", "Build over ice and stir.",
      ["#d8403a"], ["ice"]),
    D("Sex on the Beach", "vodka", "highball", "highball", [[40, "vodka"], [20, "peach schnapps"], [40, "orange juice"], [40, "cranberry juice"]],
      "Orange slice", "Pour the vodka, schnapps and orange juice over ice, then let the cranberry settle through it.",
      ["#d0304a", "#f5a13a"], ["ice", "layered"]),
    D("Harvey Wallbanger", "vodka", "highball", "highball", [[45, "vodka"], [90, "orange juice"], [15, "galliano"]],
      "Orange slice", "Build the vodka and orange juice over ice, then float the Galliano on top.",
      ["#f5a830", "#f2d020"], ["ice", "float"]),
    D("Kamikaze", "vodka", "sour", "shot", [[30, "vodka"], [30, "orange liqueur"], [30, "lime"]],
      "Lime wedge", "Shake hard with ice and strain into shot glasses, or one chilled coupe.",
      ["#eef0cc"]),
    D("Lemon Drop", "vodka", "sour", "martini", [[45, "vodka"], [20, "orange liqueur"], [25, "lemon"], [10, "simple syrup"], ["rim", "sugar"]],
      "Sugared rim", "Sugar the rim, shake the rest with ice and strain in.",
      ["#f2e28a"], ["sugar"]),
    D("French Martini", "vodka", "sour", "coupe", [[45, "vodka"], [15, "raspberry liqueur"], [45, "pineapple juice"]],
      "Raspberry", "Shake hard: the pineapple throws a fine pink foam. Strain into a chilled coupe.",
      ["#d8607a"], ["foam"]),
    D("Passion Fruit Martini", "vodka", "sour", "coupe", [[45, "vodka"], [15, "passion fruit syrup"], [15, "lime"], [10, "simple syrup"], [60, "sparkling wine", true]],
      "Half a passion fruit", "Shake with ice and strain into a chilled coupe. Traditionally served with a small glass of sparkling wine on the side.",
      ["#f2b830"], ["foam"], "Pornstar Martini"),
    D("Appletini", "vodka", "sour", "martini", [[45, "vodka"], [30, "apple liqueur"], [7.5, "lemon"]],
      "Apple slice", "Shake with ice and strain into a chilled glass.",
      ["#b6e05a"], [], "Apple Martini"),
    D("Blue Lagoon", "vodka", "highball", "highball", [[45, "vodka"], [20, "blue curacao"], [120, "lemon-lime soda"]],
      "Lemon wheel and a cherry", "Build over ice and stir.",
      ["#3aa0e6"], ["ice", "bubbles"]),
    D("Mudslide", "vodka", "creamy", "rocks", [[30, "vodka"], [30, "coffee liqueur"], [30, "irish cream"], [30, "cream"]],
      "Grated chocolate", "Shake everything with ice and strain over fresh ice, or blend with ice for a frozen one.",
      ["#9a6a4a"], ["ice"]),
    D("Godmother", "vodka", "stirred", "rocks", [[45, "vodka"], [15, "amaretto"]],
      "None", "Pour both over ice and stir.",
      ["#e8d8b0"], ["ice"]),
    D("Vodka Martini", "vodka", "stirred", "martini", [[60, "vodka"], [10, "dry vermouth"]],
      "Lemon twist or an olive", "Stir long and cold and strain into a chilled glass.",
      ["#eef2f2"], [], "Kangaroo"),
    D("Russian Spring Punch", "vodka", "sparkling", "highball", [[25, "vodka"], [25, "lemon"], [15, "creme de cassis"], [10, "simple syrup"], [60, "sparkling wine"]],
      "Lemon slice and berries", "Shake the vodka, lemon, cassis and syrup, strain over ice and top with sparkling wine.",
      ["#c0405a"], ["ice", "bubbles"]),

    // ----------------------------------------------------------------- rum
    D("Daiquiri", "rum", "sour", "coupe", [[60, "white rum"], [25, "lime"], [15, "simple syrup"]],
      "Lime wheel", "Shake hard with ice and strain into a chilled coupe. Nothing to hide behind, so taste and adjust.",
      ["#eef0d4"]),
    D("Hemingway Daiquiri", "rum", "sour", "coupe", [[60, "white rum"], [40, "grapefruit juice"], [15, "maraschino"], [15, "lime"]],
      "Lime wheel", "Shake hard with ice and strain into a chilled coupe.",
      ["#f2e6d0"], [], "Hemingway Special"),
    D("Mojito", "rum", "highball", "highball", [[45, "white rum"], [20, "lime"], [20, "simple syrup"], ["8 leaves", "mint"], [60, "soda water"]],
      "Mint sprig", "Press the mint gently into the lime and syrup, add rum and crushed ice, stir, then top with soda.",
      ["#e2f0c8"], ["crushed", "bubbles"]),
    D("Cuba Libre", "rum", "highball", "highball", [[50, "white rum"], [120, "cola"], [10, "lime"]],
      "Lime wedge", "Squeeze the lime into a glass of ice, add rum and top with cola.",
      ["#3b1a0e"], ["ice", "bubbles"], "Rum and Coke"),
    D("Dark and Stormy", "rum", "highball", "highball", [[60, "dark rum"], [100, "ginger beer"], [10, "lime", true]],
      "Lime wedge", "Fill with ice and ginger beer, then pour the dark rum over the top so it clouds down through the glass.",
      ["#d8c090", "#5a2a10"], ["ice", "bubbles", "layered"]),
    D("Mai Tai", "rum", "tiki", "rocks", [[60, "dark rum"], [15, "orange liqueur"], [15, "orgeat"], [22.5, "lime"], [7.5, "simple syrup"]],
      "Spent lime shell and a mint sprig", "Shake with crushed ice and pour the lot into the glass, ice and all.",
      ["#d9a04a"], ["crushed"]),
    D("Piña Colada", "rum", "tiki", "hurricane", [[50, "white rum"], [30, "cream of coconut"], [50, "pineapple juice"]],
      "Pineapple wedge and a cherry", "Blend with a cup of ice until smooth, or shake hard and pour over crushed ice.",
      ["#f5ecc4"], ["crushed"]),
    D("Planter's Punch", "rum", "tiki", "highball", [[45, "dark rum"], [22.5, "lime"], [15, "simple syrup"], [5, "grenadine"], ["2 dashes", "angostura"], [30, "soda water", true]],
      "Orange slice and a cherry", "Shake with ice, strain over fresh ice and lengthen with a splash of soda if you like.",
      ["#c8502a"], ["ice"]),
    D("Zombie", "rum", "tiki", "tiki", [[45, "white rum"], [45, "dark rum"], [15, "overproof rum"], [22.5, "lime"], [15, "grapefruit juice"], [15, "falernum"], [5, "grenadine"], ["6 drops", "absinthe"], ["1 dash", "angostura"]],
      "Mint sprig", "Blend briefly with crushed ice or shake hard, and pour everything into a tall mug. Serious strength: limit two.",
      ["#c8642a"], ["crushed"]),
    D("Hurricane", "rum", "tiki", "hurricane", [[60, "dark rum"], [30, "passion fruit syrup"], [30, "lime"], [30, "orange juice"], [5, "grenadine"]],
      "Orange slice and a cherry", "Shake with ice and strain over fresh ice.",
      ["#e05a3a"], ["ice"]),
    D("Jungle Bird", "rum", "tiki", "rocks", [[45, "dark rum"], [22.5, "campari"], [45, "pineapple juice"], [15, "lime"], [15, "simple syrup"]],
      "Pineapple leaf", "Shake with ice and strain over fresh ice. Bitter and tropical at once.",
      ["#d0503a"], ["ice", "foam"]),
    D("Old Cuban", "rum", "sparkling", "coupe", [[45, "dark rum"], [22.5, "lime"], [30, "simple syrup"], ["6 leaves", "mint"], ["2 dashes", "angostura"], [60, "sparkling wine"]],
      "Mint leaf", "Shake everything except the wine with ice, double strain into a coupe and top with sparkling wine.",
      ["#e8d890"], ["bubbles"]),
    D("El Presidente", "rum", "stirred", "coupe", [[45, "white rum"], [22.5, "dry vermouth"], [7.5, "orange liqueur"], ["1 barspoon", "grenadine"]],
      "Orange peel", "Stir with ice and strain into a chilled coupe.",
      ["#e8903a"]),
    D("Hotel Nacional", "rum", "sour", "coupe", [[45, "white rum"], [30, "pineapple juice"], [15, "apricot brandy"], [15, "lime"], [7.5, "simple syrup"]],
      "Lime wheel", "Shake with ice and strain into a chilled coupe.",
      ["#f2c86a"]),
    D("Mary Pickford", "rum", "sour", "coupe", [[60, "white rum"], [60, "pineapple juice"], [5, "maraschino"], [5, "grenadine"]],
      "Cherry", "Shake with ice and strain into a chilled coupe.",
      ["#f0a0a0"], ["foam"]),
    D("Blue Hawaii", "rum", "tiki", "hurricane", [[22.5, "white rum"], [22.5, "vodka"], [15, "blue curacao"], [90, "pineapple juice"], [22.5, "lemon"], [15, "simple syrup"]],
      "Pineapple wedge and a cherry", "Shake with ice and strain over crushed ice.",
      ["#2ab0d0"], ["crushed"]),
    D("Caipirinha", "rum", "sour", "rocks", [[60, "cachaca"], ["½ lime", "lime"], ["2 tsp", "sugar"]],
      "None", "Cut the lime into wedges, muddle them hard with the sugar in the glass, then fill with crushed ice and the cachaça and stir.",
      ["#eaf0c8"], ["crushed"]),
    D("Ti' Punch", "rum", "stirred", "rocks", [[50, "rhum agricole"], ["a coin of peel", "lime"], ["1 barspoon", "simple syrup"]],
      "None", "Squeeze the lime disc into the glass, add the syrup and rum and stir. Ice is optional; tradition says none.",
      ["#f0ecd8"]),
    D("Queen's Park Swizzle", "rum", "tiki", "collins", [[60, "dark rum"], [22.5, "lime"], [22.5, "simple syrup"], ["8 leaves", "mint"], ["4 dashes", "angostura"]],
      "Mint sprig", "Press the mint into the glass, add rum, lime and syrup and pack with crushed ice. Swizzle until frosty, then dash the bitters on top.",
      ["#e6d27a", "#8a2a1a"], ["crushed", "float"]),
    D("Yellow Bird", "rum", "sour", "coupe", [[30, "white rum"], [15, "galliano"], [15, "orange liqueur"], [15, "lime"]],
      "Lime wheel", "Shake with ice and strain into a chilled coupe.",
      ["#f2d24a"]),
    D("Corn 'n' Oil", "rum", "stirred", "rocks", [[60, "dark rum"], [15, "falernum"], ["2 dashes", "angostura"], ["a wedge", "lime", true]],
      "Lime wedge", "Build over crushed ice and stir. The dark rum floats like oil on the paler falernum.",
      ["#e6d8a0", "#4a1a0a"], ["crushed", "float"]),
    D("Airmail", "rum", "sparkling", "flute", [[30, "dark rum"], [15, "lime"], [15, "honey"], [60, "sparkling wine"]],
      "Lime twist", "Shake the rum, lime and honey with ice, strain into a flute and top with sparkling wine.",
      ["#f2d890"], ["bubbles"]),
    D("Between the Sheets", "rum", "sour", "coupe", [[30, "white rum"], [30, "cognac"], [30, "orange liqueur"], [20, "lemon"]],
      "Orange peel", "Shake with ice and strain into a chilled coupe.",
      ["#ecc680"]),
    D("Long Island Iced Tea", "other", "highball", "highball", [[15, "vodka"], [15, "gin"], [15, "white rum"], [15, "tequila"], [15, "orange liqueur"], [25, "lemon"], [30, "simple syrup"], [60, "cola"]],
      "Lemon wedge", "Shake everything but the cola with ice, strain over fresh ice and top with a splash of cola. No tea involved.",
      ["#a8642a"], ["ice"]),

    // ------------------------------------------------------ tequila & mezcal
    D("Margarita", "tequila", "sour", "margarita", [[50, "tequila"], [20, "orange liqueur"], [15, "lime"], ["rim", "salt", true]],
      "Salted rim and a lime wheel", "Salt half the rim, shake the rest hard with ice and strain in.",
      ["#e6ecb0"], ["salt"]),
    D("Tommy's Margarita", "tequila", "sour", "rocks", [[60, "tequila"], [30, "lime"], [15, "agave"]],
      "Lime wheel", "Shake with ice and strain over fresh ice. No liqueur, so the agave comes through.",
      ["#eef0c0"], ["ice"]),
    D("Paloma", "tequila", "highball", "highball", [[50, "tequila"], [15, "lime"], [100, "grapefruit soda"], ["a pinch", "salt"]],
      "Grapefruit wedge", "Add tequila, lime and a pinch of salt to a glass of ice and top with grapefruit soda.",
      ["#f5c6b0"], ["ice", "bubbles"]),
    D("Tequila Sunrise", "tequila", "highball", "highball", [[45, "tequila"], [90, "orange juice"], [15, "grenadine"]],
      "Orange slice and a cherry", "Build tequila and orange juice over ice, then pour the grenadine down the side so it sinks and rises back up as a sunrise.",
      ["#c0203a", "#f5a030"], ["ice", "layered"]),
    D("Ranch Water", "tequila", "highball", "highball", [[50, "tequila"], [30, "lime"], [120, "soda water"]],
      "Lime wedge", "Build over ice. Dry, sharp and very easy.",
      ["#eef4e6"], ["ice", "bubbles"]),
    D("El Diablo", "tequila", "highball", "highball", [[45, "tequila"], [15, "creme de cassis"], [15, "lime"], [90, "ginger beer"]],
      "Lime wedge", "Build tequila and lime over ice, top with ginger beer and drizzle the cassis in last.",
      ["#e8d0a0", "#a02a4a"], ["ice", "bubbles", "layered"]),
    D("Batanga", "tequila", "highball", "highball", [[50, "tequila"], [15, "lime"], [120, "cola"], ["rim", "salt"]],
      "Salted rim", "Salt the rim, add ice, tequila and lime, top with cola and stir.",
      ["#3a1a0c"], ["ice", "bubbles", "salt"]),
    D("Naked and Famous", "tequila", "sour", "coupe", [[22.5, "mezcal"], [22.5, "yellow chartreuse"], [22.5, "aperol"], [22.5, "lime"]],
      "None", "Equal parts, shaken hard with ice and strained into a chilled coupe. Smoky, bitter, bright.",
      ["#f2a24a"]),
    D("Oaxaca Old Fashioned", "tequila", "stirred", "rocks", [[45, "tequila"], [15, "mezcal"], [5, "agave"], ["2 dashes", "angostura"]],
      "Flamed orange peel", "Stir with ice and strain over one large cube.",
      ["#c8802a"], ["ice"]),
    D("Mezcal Negroni", "tequila", "stirred", "rocks", [[30, "mezcal"], [30, "campari"], [30, "sweet vermouth"]],
      "Orange peel", "Stir with ice and strain over a large cube. A negroni with smoke in it.",
      ["#a8261e"], ["ice"]),
    D("Michelada", "other", "savory", "pint", [[330, "lager"], [30, "lime"], ["2 dashes", "hot sauce"], ["1 dash", "worcestershire"], ["rim", "salt"]],
      "Lime wedge and a salted rim", "Salt the rim, add lime, sauces and ice, then pour in the cold beer slowly.",
      ["#e0a030"], ["ice", "bubbles", "salt"]),

    // ------------------------------------------------------------- whiskey
    D("Old Fashioned", "whiskey", "stirred", "rocks", [[60, "bourbon"], ["1 cube", "sugar"], ["2 dashes", "angostura"], ["a splash", "water"]],
      "Orange peel", "Wet the sugar with the bitters and water and stir until it dissolves, add the whiskey and a large cube, and stir until cold.",
      ["#b86b1e"], ["ice"]),
    D("Manhattan", "whiskey", "stirred", "coupe", [[50, "rye"], [20, "sweet vermouth"], ["1 dash", "angostura"]],
      "Cherry", "Stir with ice and strain into a chilled coupe.",
      ["#7a2e14"]),
    D("Rob Roy", "whiskey", "stirred", "coupe", [[50, "scotch"], [20, "sweet vermouth"], ["1 dash", "angostura"]],
      "Cherry", "A Manhattan made with Scotch. Stir with ice and strain.",
      ["#8a3a18"]),
    D("Boulevardier", "whiskey", "stirred", "rocks", [[45, "bourbon"], [30, "campari"], [30, "sweet vermouth"]],
      "Orange peel", "Stir with ice and strain over a large cube. Warmer and rounder than a negroni.",
      ["#8e1d17"], ["ice"]),
    D("Sazerac", "whiskey", "stirred", "rocks", [[60, "rye"], ["1 cube", "sugar"], ["3 dashes", "peychauds"], ["1 rinse", "absinthe"]],
      "Lemon peel, expressed and discarded", "Rinse a chilled glass with absinthe. Stir the rye, sugar and bitters with ice and strain into it, no ice in the glass.",
      ["#a2522a"]),
    D("Vieux Carré", "whiskey", "stirred", "rocks", [[30, "rye"], [30, "cognac"], [30, "sweet vermouth"], ["1 barspoon", "benedictine"], ["2 dashes", "peychauds"], ["2 dashes", "angostura"]],
      "Cherry and a lemon twist", "Stir with ice and strain over a large cube.",
      ["#8c3a1c"], ["ice"]),
    D("Rusty Nail", "whiskey", "stirred", "rocks", [[45, "scotch"], [25, "drambuie"]],
      "Lemon twist", "Pour both over ice and stir.",
      ["#c98a2c"], ["ice"]),
    D("Godfather", "whiskey", "stirred", "rocks", [[45, "scotch"], [15, "amaretto"]],
      "None", "Pour both over ice and stir.",
      ["#b8741f"], ["ice"]),
    D("Whiskey Sour", "whiskey", "sour", "rocks", [[45, "bourbon"], [25, "lemon"], [20, "simple syrup"], [20, "egg", true], ["3 drops", "angostura", true]],
      "Cherry and an orange slice", "Shake without ice if you use egg white, then again with ice. Strain over fresh ice.",
      ["#e3b35a"], ["ice", "foam"]),
    D("New York Sour", "whiskey", "sour", "rocks", [[60, "rye"], [25, "lemon"], [20, "simple syrup"], [20, "red wine"]],
      "Lemon peel", "Shake the whiskey, lemon and syrup with ice, strain over fresh ice, then pour the wine gently over the back of a spoon so it floats.",
      ["#e3b35a", "#6d1a2a"], ["ice", "float"]),
    D("Gold Rush", "whiskey", "sour", "rocks", [[60, "bourbon"], [22.5, "lemon"], [22.5, "honey"]],
      "Lemon twist", "Shake with ice and strain over one large cube.",
      ["#d9a03a"], ["ice"]),
    D("Brown Derby", "whiskey", "sour", "coupe", [[45, "bourbon"], [30, "grapefruit juice"], [15, "honey"]],
      "Grapefruit twist", "Shake with ice and strain into a chilled coupe.",
      ["#e0a068"]),
    D("Penicillin", "whiskey", "sour", "rocks", [[60, "scotch"], [22.5, "lemon"], [20, "honey"], ["3 slices", "ginger"], [7.5, "peated scotch"]],
      "Candied ginger", "Muddle the ginger in the honey and lemon, add the Scotch and shake with ice. Strain over fresh ice and float the peated whisky on top.",
      ["#d6a24c", "#b87420"], ["ice", "float"]),
    D("Paper Plane", "whiskey", "sour", "coupe", [[22.5, "bourbon"], [22.5, "aperol"], [22.5, "amaro nonino"], [22.5, "lemon"]],
      "None", "Four equal parts, shaken with ice and strained into a chilled coupe.",
      ["#e07a36"]),
    D("Ward Eight", "whiskey", "sour", "coupe", [[60, "rye"], [15, "lemon"], [15, "orange juice"], [10, "grenadine"]],
      "Cherry", "Shake with ice and strain into a chilled coupe.",
      ["#d86a3c"]),
    D("Whiskey Smash", "whiskey", "sour", "rocks", [[60, "bourbon"], ["3 wedges", "lemon"], ["8 leaves", "mint"], [22.5, "simple syrup"]],
      "Mint sprig", "Muddle the lemon wedges and mint in the syrup, add whiskey and shake with ice. Strain over crushed ice.",
      ["#d8b25a"], ["crushed"]),
    D("Mint Julep", "whiskey", "stirred", "julep", [[60, "bourbon"], [15, "simple syrup"], ["10 leaves", "mint"]],
      "A big bunch of mint", "Press the mint gently in the syrup, add bourbon, pack the cup with crushed ice and stir until the outside frosts. Mound more ice on top.",
      ["#d4a94a"], ["crushed"]),
    D("Irish Coffee", "whiskey", "hot", "toddy", [[40, "irish whiskey"], [90, "coffee"], ["1 tsp", "sugar"], [30, "cream"]],
      "None", "Warm the glass, stir sugar into the coffee and whiskey, then float lightly whipped cream on top. Drink through the cream.",
      ["#3b2314", "#f3e8d2"], ["hot", "float"]),
    D("Hot Toddy", "whiskey", "hot", "toddy", [[45, "scotch"], [15, "honey"], [15, "lemon"], [100, "hot water"]],
      "Lemon wheel studded with cloves", "Stir honey into hot water until it dissolves, then add the whisky and lemon.",
      ["#d9a24a"], ["hot"]),
    D("Whisky Highball", "whiskey", "highball", "highball", [[45, "scotch"], [120, "soda water"]],
      "Lemon twist", "Fill a glass with ice, add the whisky, top with very cold soda and give it one stir.",
      ["#e6c47a"], ["ice", "bubbles"]),
    D("Whiskey Ginger", "whiskey", "highball", "highball", [[50, "irish whiskey"], [120, "ginger ale"]],
      "Lime wedge", "Build over ice and stir.",
      ["#e0b060"], ["ice", "bubbles"]),
    D("Blood and Sand", "whiskey", "sour", "coupe", [[22.5, "scotch"], [22.5, "cherry liqueur"], [22.5, "sweet vermouth"], [22.5, "orange juice"]],
      "Orange peel", "Equal parts, shaken with ice and strained into a chilled coupe.",
      ["#9c3a22"]),
    D("Tipperary", "whiskey", "stirred", "coupe", [[50, "irish whiskey"], [25, "sweet vermouth"], [15, "green chartreuse"]],
      "Orange peel", "Stir with ice and strain into a chilled coupe.",
      ["#a8602a"]),
    D("Trinidad Sour", "whiskey", "sour", "coupe", [[45, "angostura"], [30, "orgeat"], [22.5, "lemon"], [15, "rye"]],
      "None", "Yes, a full measure of bitters. Shake with ice and strain into a chilled coupe.",
      ["#9a2a1a"]),

    // -------------------------------------------------------------- brandy
    D("Sidecar", "brandy", "sour", "coupe", [[50, "cognac"], [20, "orange liqueur"], [20, "lemon"], ["rim", "sugar", true]],
      "Orange peel", "Shake with ice and strain into a chilled coupe, sugar-rimmed if you like.",
      ["#d9953a"], ["sugar"]),
    D("Brandy Alexander", "brandy", "creamy", "coupe", [[30, "cognac"], [30, "creme de cacao"], [30, "cream"]],
      "Grated nutmeg", "Shake hard with ice and strain into a chilled coupe.",
      ["#dcc6a2"], [], "Alexander"),
    D("Stinger", "brandy", "stirred", "rocks", [[50, "cognac"], [20, "creme de menthe"]],
      "Mint sprig", "Stir with ice and strain over crushed ice.",
      ["#e8e4c0"], ["crushed"]),
    D("French Connection", "brandy", "stirred", "rocks", [[35, "cognac"], [35, "amaretto"]],
      "None", "Pour both over ice and stir.",
      ["#b0621e"], ["ice"]),
    D("Brandy Crusta", "brandy", "sour", "wine", [[52.5, "cognac"], [7.5, "maraschino"], [5, "orange liqueur"], [15, "lemon"], ["1 barspoon", "simple syrup"], ["2 dashes", "angostura"], ["rim", "sugar"]],
      "A wide spiral of lemon peel lining the glass", "Sugar the rim and line the glass with the peel. Shake the rest with ice and strain in.",
      ["#d89a44"], ["sugar"]),
    D("Jack Rose", "brandy", "sour", "coupe", [[45, "apple brandy"], [20, "lime"], [15, "grenadine"]],
      "Apple slice", "Shake with ice and strain into a chilled coupe.",
      ["#d64a5a"]),
    D("Horse's Neck", "brandy", "highball", "highball", [[40, "cognac"], [120, "ginger ale"], ["1 dash", "angostura", true]],
      "One long spiral of lemon peel", "Hang the peel inside the glass, add ice and brandy and top with ginger ale.",
      ["#e0b068"], ["ice", "bubbles"]),
    D("Pisco Sour", "brandy", "sour", "coupe", [[60, "pisco"], [30, "lime"], [20, "simple syrup"], [30, "egg"], ["3 drops", "angostura"]],
      "Bitters dotted on the foam", "Shake without ice, then with ice. Strain into a coupe and dot the bitters on the foam.",
      ["#f0e8c4"], ["foam"]),
    D("Porto Flip", "brandy", "creamy", "coupe", [[15, "cognac"], [45, "port"], ["1 yolk", "egg"]],
      "Grated nutmeg", "Shake very hard with ice and strain into a chilled coupe.",
      ["#8a3d3a"]),
    D("Champagne Cocktail", "brandy", "sparkling", "flute", [["1 cube", "sugar"], ["2 dashes", "angostura"], [10, "cognac", true], [90, "sparkling wine"]],
      "Orange twist", "Soak the sugar cube in bitters and drop it in a flute, add the brandy and top slowly with sparkling wine.",
      ["#f0d27a"], ["bubbles"]),

    // ------------------------------------------------ wine, bubbles & aperitifs
    D("Aperol Spritz", "wine", "spritz", "wine", [[90, "sparkling wine"], [60, "aperol"], [30, "soda water"]],
      "Orange slice", "Fill a wine glass with ice: prosecco first, then Aperol, then a splash of soda.",
      ["#f26a2a"], ["ice", "bubbles"], "Spritz"),
    D("Hugo", "wine", "spritz", "wine", [[90, "sparkling wine"], [30, "elderflower liqueur"], [30, "soda water"], ["4 leaves", "mint"], ["a wedge", "lime"]],
      "Mint and lime", "Clap the mint and drop it in a glass of ice with the lime, add elderflower and prosecco and top with soda.",
      ["#ecf0d0"], ["ice", "bubbles"], "Hugo Spritz"),
    D("Americano", "wine", "highball", "highball", [[30, "campari"], [30, "sweet vermouth"], [60, "soda water"]],
      "Orange slice", "Build over ice and top with soda.",
      ["#c0392b"], ["ice", "bubbles"]),
    D("Negroni Sbagliato", "wine", "spritz", "rocks", [[30, "campari"], [30, "sweet vermouth"], [30, "sparkling wine"]],
      "Orange slice", "The 'mistaken' negroni: sparkling wine where the gin should be. Build over ice.",
      ["#b8322a"], ["ice", "bubbles"]),
    D("Garibaldi", "wine", "highball", "highball", [[45, "campari"], [120, "orange juice"]],
      "Orange wedge", "Build over ice. Freshly squeezed and frothy orange juice is the whole point.",
      ["#e8543a"], ["ice", "foam"]),
    D("Bicicletta", "wine", "spritz", "wine", [[45, "campari"], [90, "white wine"], [30, "soda water"]],
      "Orange slice", "Build over ice in a wine glass and top with soda.",
      ["#e0503a"], ["ice", "bubbles"]),
    D("Mimosa", "wine", "sparkling", "flute", [[75, "orange juice"], [75, "sparkling wine"]],
      "Orange twist", "Half orange juice, half sparkling wine. Pour the wine first so it doesn't foam over.",
      ["#f5b43a"], ["bubbles"]),
    D("Bellini", "wine", "sparkling", "flute", [[50, "peaches"], [100, "sparkling wine"]],
      "None", "Purée ripe white peaches, spoon into a flute and top slowly with prosecco, stirring gently.",
      ["#f7c28a"], ["bubbles"]),
    D("Kir", "wine", "sparkling", "wine", [[10, "creme de cassis"], [90, "white wine"]],
      "None", "Cassis in the glass, cold dry white wine on top.",
      ["#b0364a"]),
    D("Kir Royale", "wine", "sparkling", "flute", [[10, "creme de cassis"], [90, "sparkling wine"]],
      "None", "Cassis in the flute, sparkling wine on top.",
      ["#b8405a"], ["bubbles"]),
    D("Death in the Afternoon", "wine", "sparkling", "flute", [[20, "absinthe"], [120, "sparkling wine"]],
      "None", "Absinthe in a flute, topped slowly with cold sparkling wine until it turns milky.",
      ["#e6efd0"], ["bubbles"]),
    D("Adonis", "wine", "stirred", "coupe", [[45, "fino sherry"], [45, "sweet vermouth"], ["2 dashes", "orange bitters"]],
      "Orange peel", "Stir with ice and strain into a chilled coupe. Low-proof and nutty.",
      ["#a8541e"]),
    D("Bamboo", "wine", "stirred", "coupe", [[45, "fino sherry"], [45, "dry vermouth"], ["2 dashes", "angostura"], ["2 dashes", "orange bitters"]],
      "Lemon twist", "Stir with ice and strain into a chilled coupe.",
      ["#eadca0"]),
    D("Pimm's Cup", "other", "highball", "highball", [[50, "pimms"], [120, "lemon-lime soda"], ["2 slices", "lemon", true], ["a few leaves", "mint", true]],
      "Cucumber, strawberry and mint", "Fill a glass with ice and fruit, add Pimm's and top with lemonade-style soda.",
      ["#b0572c"], ["ice", "bubbles"]),

    // --------------------------------------------------------------- other
    D("Amaretto Sour", "other", "sour", "rocks", [[45, "amaretto"], [15, "bourbon", true], [30, "lemon"], [7.5, "simple syrup"], [20, "egg", true]],
      "Cherry and a lemon twist", "Shake without ice, then with ice, and strain over fresh ice. The bourbon keeps it from getting too sweet.",
      ["#e6b04a"], ["ice", "foam"]),
    D("Midori Sour", "other", "sour", "rocks", [[45, "melon liqueur"], [15, "vodka"], [15, "lemon"], [15, "lime"], [30, "soda water", true]],
      "Lemon wheel and a cherry", "Shake with ice, strain over fresh ice and add a splash of soda.",
      ["#6ad24a"], ["ice"]),
    D("Grasshopper", "other", "creamy", "coupe", [[30, "creme de menthe"], [30, "creme de cacao"], [30, "cream"]],
      "Mint leaf", "Shake hard with ice and strain into a chilled coupe. Tastes like an after-dinner mint.",
      ["#9ad69a"]),
    D("Golden Dream", "other", "creamy", "coupe", [[20, "galliano"], [20, "orange liqueur"], [20, "orange juice"], [10, "cream"]],
      "None", "Shake with ice and strain into a chilled coupe.",
      ["#f5d27a"]),
    D("B-52", "other", "shot", "shot", [[20, "coffee liqueur"], [20, "irish cream"], [20, "orange liqueur"]],
      "None", "Layer in this order over the back of a spoon: coffee liqueur, Irish cream, orange liqueur.",
      ["#2a140c", "#d9b48a", "#f0dca0"], ["layered"]),

    // ----------------------------------------------------------- zero-proof
    D("Nojito", "none", "zero", "highball", [[20, "lime"], [20, "simple syrup"], ["8 leaves", "mint"], [120, "soda water"]],
      "Mint sprig", "Press the mint into the lime and syrup, fill with crushed ice and top with soda.",
      ["#e2f0c8"], ["crushed", "bubbles"], "Virgin Mojito"),
    D("Shirley Temple", "none", "zero", "highball", [[150, "ginger ale"], [15, "grenadine"], [10, "lime", true]],
      "Cherries, lots of them", "Fill with ice and ginger ale, then pour the grenadine in so it drifts down.",
      ["#f5d0b0", "#e05070"], ["ice", "bubbles", "layered"]),
    D("Roy Rogers", "none", "zero", "highball", [[150, "cola"], [15, "grenadine"]],
      "Cherry", "Build over ice and stir.",
      ["#4a1a10"], ["ice", "bubbles"]),
    D("Arnold Palmer", "none", "zero", "highball", [[120, "iced tea"], [120, "lemonade"]],
      "Lemon wheel", "Half iced tea, half lemonade, over ice.",
      ["#c88a3a"], ["ice"], "Half and Half"),
    D("Virgin Mary", "none", "zero", "highball", [[120, "tomato juice"], [15, "lemon"], ["2 dashes", "worcestershire"], ["2 dashes", "hot sauce"], ["a pinch", "salt"], ["a pinch", "pepper"]],
      "Celery stalk", "Roll between two tins to mix without frothing, and pour over ice.",
      ["#b8231e"], ["ice"]),
    D("Nada Colada", "none", "zero", "hurricane", [[45, "cream of coconut"], [90, "pineapple juice"], [10, "lime"]],
      "Pineapple wedge", "Blend with ice until smooth, or shake hard and pour over crushed ice.",
      ["#f5ecc4"], ["crushed"], "Virgin Piña Colada"),
    D("Cinderella", "none", "zero", "highball", [[60, "orange juice"], [60, "pineapple juice"], [15, "lemon"], [5, "grenadine"], [60, "soda water"]],
      "Orange slice", "Shake the juices and grenadine with ice, strain over fresh ice and top with soda.",
      ["#f5b04a"], ["ice", "bubbles"]),
    D("Lime Rickey", "none", "zero", "highball", [[30, "lime"], [20, "simple syrup"], [150, "soda water"]],
      "Lime wedge", "Squeeze the lime into a glass of ice, add syrup and top with soda.",
      ["#eef4dc"], ["ice", "bubbles"]),
    D("Espresso Tonic", "none", "zero", "highball", [[150, "tonic"], [30, "espresso"]],
      "Orange twist", "Fill with ice and tonic, then pour a fresh espresso slowly over the top.",
      ["#eee8dc", "#5a3014"], ["ice", "bubbles", "float"]),
    D("Ginger Mule", "none", "zero", "mug", [[15, "lime"], [150, "ginger beer"], ["4 leaves", "mint", true]],
      "Lime wheel and mint", "Build over ice in a copper mug and stir.",
      ["#ece2c0"], ["ice", "bubbles"], "Virgin Mule"),
    D("Cranberry Fizz", "none", "zero", "highball", [[90, "cranberry juice"], [15, "lime"], [90, "soda water"]],
      "Lime wheel", "Build over ice and stir once.",
      ["#c8304a"], ["ice", "bubbles"]),
    D("Virgin Paloma", "none", "zero", "highball", [[90, "grapefruit juice"], [15, "lime"], [10, "simple syrup"], [90, "soda water"], ["a pinch", "salt"]],
      "Grapefruit wedge and a salted rim", "Salt the rim, build over ice and top with soda.",
      ["#f6c8b4"], ["ice", "bubbles", "salt"]),

    // the zero-proof bar proper: built like drinks, not like juice
    D("Nogroni", "none", "zero", "rocks", [[30, "na gin"], [30, "na aperitif"], [20, "iced tea"], [5, "simple syrup"]],
      "Orange peel", "Stir with ice and strain over a large cube. Strong black tea stands in for the vermouth: it brings the tannin and weight that a bitter aperitif alone lacks.",
      ["#a8261e"], ["ice"], "Zero-Proof Negroni"),
    D("Zero-Proof Spritz", "none", "zero", "wine", [[60, "na aperitif"], [90, "na sparkling"], [30, "soda water"]],
      "Orange slice", "Fill a wine glass with ice: alcohol-free sparkling first, then the aperitif, then a splash of soda.",
      ["#e8502a"], ["ice", "bubbles"]),
    D("Zero-Proof French 75", "none", "zero", "flute", [[30, "na gin"], [15, "lemon"], [15, "simple syrup"], [60, "na sparkling"]],
      "Lemon twist", "Shake the zero-proof gin, lemon and syrup with ice, strain into a flute and top with alcohol-free sparkling.",
      ["#f2e6a8"], ["bubbles"]),
    D("Zero-Proof G&T", "none", "zero", "highball", [[50, "na gin"], [150, "tonic"]],
      "Lime wedge and a cucumber ribbon", "Fill the glass with ice, add the zero-proof gin and top with cold tonic. A heavier pour than usual, because there is no alcohol to carry the botanicals.",
      ["#eef4f0"], ["ice", "bubbles"]),
    D("Americano Zero", "none", "zero", "highball", [[45, "na aperitif"], [90, "soda water"]],
      "Orange slice", "Build over ice and top with soda.",
      ["#d0402e"], ["ice", "bubbles"]),
    D("Zero-Proof Southside", "none", "zero", "coupe", [[60, "na gin"], [30, "lime"], [15, "simple syrup"], ["6 leaves", "mint"]],
      "Mint leaf", "Shake everything hard with ice so the mint bruises, then double strain into a chilled coupe.",
      ["#d4ecb4"]),
    D("Zero-Proof Michelada", "none", "zero", "pint", [[330, "na beer"], [30, "lime"], ["2 dashes", "hot sauce"], ["1 dash", "worcestershire"], ["rim", "salt"]],
      "Lime wedge and a salted rim", "Salt the rim, add lime, sauces and ice, then pour in the cold non-alcoholic beer slowly.",
      ["#e0a030"], ["ice", "bubbles", "salt"]),
    D("Cucumber Cooler", "none", "zero", "collins", [["4 slices", "cucumber"], [25, "lime"], [20, "simple syrup"], ["6 leaves", "mint"], [120, "soda water"]],
      "Cucumber ribbon and mint", "Muddle the cucumber and mint in the lime and syrup, fill with ice and top with soda. Stir from the bottom.",
      ["#dcefc8"], ["ice", "bubbles"]),
    D("Raspberry Shrub Soda", "none", "zero", "highball", [["6 berries", "raspberries"], [10, "cider vinegar"], [25, "simple syrup"], [120, "soda water"]],
      "Raspberries", "Muddle the berries into the syrup and vinegar, strain over ice and top with soda. The vinegar does what the booze would: a bite that makes it taste like a grown-up drink.",
      ["#e0506a"], ["ice", "bubbles"]),
    D("Ginger Honey Sour", "none", "zero", "rocks", [[30, "lemon"], [25, "honey"], ["3 slices", "ginger"], [60, "iced tea"], [20, "egg", true]],
      "Candied ginger", "Muddle the ginger in the honey and lemon, add the tea and shake hard with ice. Strain over fresh ice. Shake without ice first if you use egg white.",
      ["#d8a24c"], ["ice", "foam"]),
    D("Peach Tea Fizz", "none", "zero", "collins", [[90, "iced tea"], [30, "peaches"], [15, "lemon"], [60, "soda water"]],
      "Peach slice", "Shake the tea, peach purée and lemon with ice, strain over fresh ice and lengthen with soda.",
      ["#e8a060"], ["ice", "bubbles"]),
    D("Tropical Zero", "none", "zero", "hurricane", [[90, "pineapple juice"], [20, "lime"], [15, "orgeat"], [15, "passion fruit syrup"]],
      "Pineapple wedge and mint", "Shake hard with ice and pour over crushed ice. All the tiki, none of the rum.",
      ["#f2c050"], ["crushed", "foam"])
  ];

  window.BARKEEP = { SHELF: SHELF, PANTRY: PANTRY, PANTRY_LABEL: PANTRY_LABEL, STARTER: STARTER, DRINKS: DRINKS, SWAPS: SWAPS };
})();
